application:
  applicationName: "catalog"
  configMap:
    enabled: true
    files:
    - nameSuffix: ""
      data:
        MYSQL_USER: "catalog"
        MYSQL_HOST:  "catalog-sql"
        MYSQL_DB_NAME: "catalog"
        KEYCLOAK_CLIENT_SECRET_KEY: "7672aea2-81ff-4aa2-affe-daf3bad10334"
        JAEGER_ENDPOINT: "http://jaeger-collector.istio-system:14268/api/traces"
        KEYCLOAK_REALM: "nordmart"
        KEYCLOAK_URL: "https://iam-keycloak-nordmart-dev.apps.binero.06p407u4.kubeapp.cloud/auth/"
        KEYCLOAK_CLIENT_BACKEND: "stakater-nordmart-backend"
        KAFKA_ADDRESS: "nordmart-kafka-bootstrap:9092"
  deployment:
    imagePullSecrets: nexus-docker-config-forked
    additionalLabels:
      appCategory: "backend"
    annotations:
    volumes: {}
    image:
      repository: stakater/stakater-nordmart-catalog
      tag: v0.0.3
    resources: 
      limits:
        memory: 1Gi 
        cpu: 0.5
      requests:
        memory: 128Mi
        cpu: 0.1
    envFrom:
    - type: configmap
      name: ""   
    env:
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: catalog-sql
          key: mysql-password
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /actuator/health
          port: 8080
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /actuator/health
          port: 8080
  service:
    ports:
    - port: 8080
      name: https
  rbac:
    create: true
    serviceAccount:
      create: true
      enabled: true

mysql:
  fullnameOverride: catalog-sql
  replication:
    enabled: false
  auth:
    username: catalog
  master:
    securityContext:
      enabled: false
    
 