applicationName: "catalog"
deployment:
  podLabels:
    app: catalog
  image:
    repository: docker.release.stakater.com:443/stakater/catalog
    tag: v0.0.2
  env:
  - name: JAEGER_ENDPOINT
    value: "jaeger-collector.istio-system:14268/api/traces"
  imagePullSecrets: "docker-registry-nexus-secret"
rbac:
  create: false
  serviceAccount:
    name: default
configMap: {}
